import './globals.css';
import { Nunito_Sans } from 'next/font/google';
import Header from './components/Header';

const font = Nunito_Sans({
  subsets: ['latin'],
  weight: ['300', '600', '800']
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=''>
      <body className={`${font.className} bg-very-light-gray dark:bg-very-dark-blue relative text-very-dark-blue-text dark:text-white overflow-y-scroll`}>
        <Header />
        <main className='mt-24 sm:mt-28 p-6'>
          {children}
        </main>
      </body>
    </html>
  );
}
